[features]
seeds = false
skip-lint = false

[programs.testnet]
airvent_subscription = "AirvENTSubscription111111111111111111111111"

[programs.devnet]
airvent_subscription = "AirvENTSubscription111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
